import request from '@/utils/request'
const json = { headers: { 'Content-Type': 'application/json' } }
export const listAccounts = () => request.get('/admin/users')
export const createAccount = payload => request.post('/admin/users', payload, json)
export const updateAccount = (id, payload) => request.put(`/admin/users/${id}`, payload, json)
export const deleteAccount = id => request.delete(`/admin/users/${id}`)
export const createAccountBatch = payload => request.post('/admin/users/batch', payload, json)
export const bulkEnableAccounts = userIds => request.post('/admin/users/bulk-enable', { userIds }, json)
export const bulkDisableAccounts = userIds => request.post('/admin/users/bulk-disable', { userIds }, json)
export const bulkDeleteAccounts = userIds => request.post('/admin/users/bulk-delete', { userIds }, json)
export const preflightAccountMigration = payload => request.post('/admin/account-migrations/preflight', payload, json)
export const listCompetitionCredentials = () => request.get('/admin/competition-credentials')
export const regenerateCompetitionPassword = id => request.post(`/admin/competition-credentials/${id}/regenerate`)
export const updateCompetitionPassword = (id, password) => request.put(`/admin/competition-credentials/${id}`, { password }, json)
export const getAdminDemoPlacement = () => request.get('/admin/demo-placement')
export const bindAdminDemoPlacement = slotId => request.post('/admin/demo-placement', { slotId }, json)
export const listAccountTemplates = () => request.get('/admin/account-templates')
export const saveAccountTemplate = payload => request.post('/admin/account-templates', payload, json)
export const completeUserProfile = fields => request.post('/user/profile', fields, json)
