import request from '@/utils/request.js'
export const listAdminCourses = () => request.get('/admin/courses')
const json = { headers: { 'Content-Type': 'application/json' } }
export const createCourse = payload => request.post('/admin/courses', payload, json)
export const updateCourse = (id, payload) => request.put(`/admin/courses/${id}`, payload, json)
export const deleteCourse = id => request.delete(`/admin/courses/${id}`)
export const listCourseChapters = id => request.get(`/admin/courses/${id}/chapters`)
export const createCourseChapter = (id, payload) => request.post(`/admin/courses/${id}/chapters`, payload, json)
export const updateCourseChapter = (courseId, chapterId, payload) => request.put(`/admin/courses/${courseId}/chapters/${chapterId}`, payload, json)
export const deleteCourseChapter = (courseId, chapterId) => request.delete(`/admin/courses/${courseId}/chapters/${chapterId}`)
export const bindCourseResource = (courseId, fileId, payload) => request.put(`/admin/courses/${courseId}/resources/${fileId}/binding`, payload, json)
export const updateCourseResourceMetadata = (courseId, fileId, payload) => request.put(`/admin/courses/${courseId}/resources/${fileId}/metadata`, payload, json)
export const uploadCourseContentImage = data => request.post('/admin/courses/content-images', data, { timeout: 0 })
export const setCourseEnabled = (id, enabled) => request.post(`/admin/courses/${id}/enabled`, null, { params: { enabled } })
export const addCourseResource = (id, payload) => request.post(`/admin/courses/${id}/resources`, payload, json)
export const setCourseResourceEnabled = (id, enabled) => request.post(`/admin/courses/resources/${id}/enabled`, null, { params: { enabled } })
export const uploadCourseResource = file => { const data = new FormData(); data.append('file', file); return request.post('/admin/course-resources/upload', data, { timeout: 0 }) }
export const listUserCourses = () => request.get('/user/courses')
export const listUserCourseChapters = id => request.get(`/user/courses/${id}/chapters`)
export const getCourseReport = id => request.get(`/user/course-reports/${id}`)
export const saveCourseReport = (id, content) => request.put(`/user/course-reports/${id}`, { courseId: id, content }, json)
export const recordCourseProgress = payload => request.post('/user/courses/progress', payload, json)
export const listCourseProgress = () => request.get('/user/courses/progress')
export const getCourseResourcePreviewUrl = resourceId => request.get(`/user/courses/resources/${resourceId}/preview-url`)
export const getCourseCoverUrl = courseId => request.get(`/user/courses/${courseId}/cover-url`)
export const getAdminCourseResourcePreviewUrl = resourceId => request.get(`/admin/courses/resources/${resourceId}/preview-url`)
export const getAdminCourseCoverUrl = courseId => request.get(`/admin/courses/${courseId}/cover-url`)
export const deliverCourseResource = (resourceId, environmentId) => request.post(`/course-resources/${resourceId}/deliver`, null, { params: { environmentId } })
export const deliverCourseResourceForUser = (resourceId, environmentId, userId) => request.post(`/course-resources/${resourceId}/deliver-for-user`, null, { params: { environmentId, userId } })
export const deliverCourseResourceToAll = resourceId => request.post(`/course-resources/${resourceId}/deliver-to-all`)
export const listCourseDeliveries = () => request.get('/course-resources/deliveries')
export const listAdminCourseDeliveries = () => request.get('/course-resources/admin-deliveries')
