<template><section class="module-page module-composed-page"><header class="module-heading"><div><h1>实训环境</h1><p>启动课程环境并选择图像标注或代码编辑工具。</p></div><el-button icon="el-icon-cpu" @click="$router.push('/training-validation')">模型验证</el-button></header><ParticipantPreviewNotice v-if="previewOnly" /><div class="module-table-wrap"><el-table v-loading="loading" :data="environments" empty-text="暂无已分配环境"><el-table-column label="课程" min-width="100"><template slot-scope="s">{{ s.row.courseLabel || s.row.courseId }}</template></el-table-column><el-table-column prop="actualState" label="运行状态" min-width="110"><template slot-scope="s"><el-tag size="small" :type="tagType(s.row.actualState)">{{ stateText(s.row.actualState) }}</el-tag></template></el-table-column><el-table-column label="课程资源" min-width="220"><template slot-scope="s"><el-button v-for="resource in resourcesFor(s.row.courseId)" :key="resource.resourceId" size="mini" :disabled="previewOnly" :loading="sendingId===resource.resourceId" @click="send(resource,s.row)">{{ resource.name }}</el-button></template></el-table-column><el-table-column label="操作" width="230" align="right"><template slot-scope="s"><el-button type="primary" size="small" :loading="busyId===s.row.environmentId" :disabled="previewOnly||isPending(s.row)" @click="start(s.row)">一键上课</el-button><el-button size="small" :disabled="previewOnly||s.row.actualState!=='RUNNING'" @click="openTools(s.row)">进入工具</el-button></template></el-table-column></el-table></div><el-dialog title="选择实训工具" :visible.sync="toolDialog" width="430px"><p>课程：{{ selectedEnvironment && (selectedEnvironment.courseLabel || selectedEnvironment.courseId) }}</p><el-radio-group v-model="selectedTool"><el-radio-button label="cvat">CVAT 图像标注</el-radio-button><el-radio-button label="vscode">VS Code</el-radio-button><el-radio-button label="jupyter">Jupyter Notebook</el-radio-button></el-radio-group><p class="tool-port">{{ toolDescription }}</p><span slot="footer"><el-button @click="toolDialog=false">取消</el-button><el-button type="primary" @click="openSelectedTool">打开工具</el-button></span></el-dialog></section></template>
<script>
import { adminParticipantPreviewTrainingEnvironmentsApi, listUserTrainingEnvironments, startUserTrainingEnvironment } from '@/api/TrainingEnvironments'
import { listUserCourses, deliverCourseResource } from '@/api/Courses'
import ParticipantPreviewNotice from '@/components/ParticipantPreviewNotice.vue'
import { getRole } from '@/utils/auth'
const { isPreviewRoute } = require('@/services/participantPreview')
export default { components:{ParticipantPreviewNotice}, data:()=>({loading:false,busyId:'',sendingId:'',environments:[],courses:[],toolDialog:false,selectedEnvironment:null,selectedTool:'cvat'}), computed:{previewOnly(){return isPreviewRoute(this.$route,getRole())},toolDescription(){return this.selectedTool==='cvat'?'CVAT：8081 起按槽位分配':this.selectedTool==='vscode'?'VS Code：9091-9094 按槽位分配':'Jupyter Notebook：8881-8884 按槽位分配'}}, created(){this.load();this.loadCourses()}, methods:{async load(){this.loading=true;try{const call=this.previewOnly?adminParticipantPreviewTrainingEnvironmentsApi:listUserTrainingEnvironments;const r=await call();const all=r.data||[];const id=this.$route.query&&this.$route.query.courseId;this.environments=id?all.filter(e=>String(e.courseId)===String(id)):all;if(id&&!this.environments.length)this.$message.info('当前课程尚未分配实训环境')}finally{this.loading=false}},async loadCourses(){const r=await listUserCourses();this.courses=r.data||[]},resourcesFor(courseId){const item=this.courses.find(c=>String(c.course.courseId)===String(courseId));return item?item.resources||[]:[]},async send(resource,environment){this.sendingId=resource.resourceId;try{await deliverCourseResource(resource.resourceId,environment.environmentId);this.$message.success('资源下发任务已提交')}finally{this.sendingId=''}},async start(row){if(this.previewOnly)return;this.busyId=row.environmentId;try{await startUserTrainingEnvironment(row.environmentId);await this.load()}finally{this.busyId=''}},openTools(row){this.selectedEnvironment=row;this.selectedTool='cvat';this.toolDialog=true},openSelectedTool(){const row=this.selectedEnvironment;const url=this.selectedTool==='cvat'?row.annotationUrl:(this.selectedTool==='vscode'?row.editorUrl:row.jupyterUrl);if(!url){this.$message.warning('当前环境尚未返回该工具地址，请等待容器就绪');return}window.open(url,'_blank','noopener,noreferrer');this.toolDialog=false},isPending(r){return['CREATING','STARTING','STOPPING','RESTORING','WAITING_DEPENDENCY'].includes(r.actualState)},stateText(s){return({RUNNING:'运行中',STOPPED:'已停止',DEGRADED:'部分异常',ERROR:'异常',STARTING:'启动中',STOPPING:'停止中',RESTORING:'还原中',WAITING_DEPENDENCY:'等待切换'})[s]||s||'未知'},tagType(s){return s==='RUNNING'?'success':(s==='ERROR'||s==='DEGRADED'?'danger':'info')}} }
</script>
