#!/usr/bin/env bash

set -Eeuo pipefail

PROJECT_NAME=match-v2
MYSQL_VOLUME=match-v2_mysql_data

log() {
  printf '[match-offline] %s\n' "$*"
}

die() {
  printf '[match-offline] ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

require_amd64() {
  case "$(uname -m)" in
    x86_64|amd64) ;;
    *) die "Only x86_64/amd64 is supported; found $(uname -m)" ;;
  esac
}

assert_safe_install_dir() {
  local path=${1:-}
  local checked_path candidate trimmed
  [[ -n "$path" ]] || die "Install directory must not be empty"
  [[ "$path" = /* ]] || die "Install directory must be an absolute path: $path"

  case "$path" in
    *//*|*/../*|*/..|*/./*|*/.) die "Install directory must be normalized: $path" ;;
  esac

  checked_path=$path
  if [[ -e "$path" ]]; then
    require_command realpath
    checked_path=$(realpath "$path")
  fi

  for candidate in "$path" "$checked_path"; do
    case "$candidate" in
      /|/root|/root/|/home|/home/|/Users|/Users/|"${HOME:-}"|"${HOME:-}/")
        die "Refusing unsafe install directory: $candidate"
        ;;
    esac
    trimmed=${candidate#/}
    [[ "$trimmed" = */* ]] || die "Install directory is too broad: $candidate"
  done
}

require_package() {
  local package_dir=$1
  local required
  for required in \
    SHA256SUMS MANIFEST.txt release.env compose.offline.yml host-identity.sh \
    images/match-v2-images.tar.gz data/mysql.sql.gz \
    data/fastdfs-tracker.tar.gz data/fastdfs-storage.tar.gz \
    data/dataset.tar.gz data/scoring.tar.gz; do
    [[ -f "$package_dir/$required" ]] || die "Release package is missing $required"
  done
}

verify_package() {
  local package_dir=$1
  require_command sha256sum
  require_package "$package_dir"
  log "Verifying release checksums"
  (cd "$package_dir" && sha256sum -c SHA256SUMS)
}

load_release_env() {
  local env_file=$1
  [[ -f "$env_file" ]] || die "Release metadata not found: $env_file"
  # release.env is generated by build-release.sh and covered by SHA256SUMS.
  # shellcheck disable=SC1090
  source "$env_file"
  [[ -n "${MATCH_RELEASE_VERSION:-}" ]] || die "MATCH_RELEASE_VERSION is missing"
}

compose_at() {
  local install_dir=$1
  shift
  (
    set -a
    # shellcheck disable=SC1090
    source "$install_dir/release.env"
    set +a
    docker compose \
      --project-name "$PROJECT_NAME" \
      --env-file "$install_dir/.env" \
      -f "$install_dir/compose.offline.yml" "$@"
  )
}

wait_for_mysql() {
  local install_dir=$1
  local attempts=${2:-60}
  local container_id status

  container_id=$(compose_at "$install_dir" ps -q mysql)
  [[ -n "$container_id" ]] || die "MySQL container was not created"

  while (( attempts > 0 )); do
    status=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container_id")
    [[ "$status" == healthy ]] && return 0
    [[ "$status" == exited || "$status" == dead ]] && die "MySQL container stopped with status $status"
    sleep 2
    attempts=$((attempts - 1))
  done

  die "Timed out waiting for MySQL to become healthy"
}

check_runtime_empty() {
  local install_dir=$1
  local runtime_dir="$install_dir/runtime"

  if [[ -d "$runtime_dir" ]] && find "$runtime_dir" -mindepth 1 -print -quit | grep -q .; then
    die "Runtime data already exists: $runtime_dir"
  fi
  if docker volume inspect "$MYSQL_VOLUME" >/dev/null 2>&1; then
    die "Docker volume already exists: $MYSQL_VOLUME"
  fi
  if docker ps -a -q --filter "label=com.docker.compose.project=$PROJECT_NAME" | grep -q .; then
    die "Containers already exist for Compose project $PROJECT_NAME"
  fi
}

install_control_files() {
  local package_dir=$1
  local install_dir=$2
  local env_file=$3

  mkdir -p "$install_dir"
  install -m 0644 "$package_dir/compose.offline.yml" "$install_dir/compose.offline.yml"
  install -m 0644 "$package_dir/release.env" "$install_dir/release.env"
  install -m 0600 "$env_file" "$install_dir/.env"
  install -m 0755 "$package_dir/_common.sh" "$install_dir/_common.sh"
  install -m 0755 "$package_dir/verify.sh" "$install_dir/verify.sh"
  install -m 0755 "$package_dir/uninstall.sh" "$install_dir/uninstall.sh"
  install -m 0755 "$package_dir/host-identity.sh" "$install_dir/host-identity.sh"
}

restore_file_archives() {
  local package_dir=$1
  local install_dir=$2
  local runtime_dir="$install_dir/runtime"

  mkdir -p \
    "$runtime_dir/fastdfs/tracker_data" \
    "$runtime_dir/fastdfs/storage_data" \
    "$runtime_dir/dataset" \
    "$runtime_dir/scoring"

  tar --numeric-owner -xzf "$package_dir/data/fastdfs-tracker.tar.gz" -C "$runtime_dir/fastdfs/tracker_data"
  tar --numeric-owner -xzf "$package_dir/data/fastdfs-storage.tar.gz" -C "$runtime_dir/fastdfs/storage_data"
  tar --numeric-owner -xzf "$package_dir/data/dataset.tar.gz" -C "$runtime_dir/dataset"
  tar --numeric-owner -xzf "$package_dir/data/scoring.tar.gz" -C "$runtime_dir/scoring"
}

load_images() {
  local package_dir=$1
  log "Loading Docker images"
  gzip -dc "$package_dir/images/match-v2-images.tar.gz" | docker load
}

restore_database() {
  local package_dir=$1
  local install_dir=$2
  local table_count

  table_count=$(compose_at "$install_dir" exec -T mysql sh -c \
    'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -Nse "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = '\''$MYSQL_DATABASE'\''"')
  [[ "$table_count" == 0 ]] || die "Target database is not empty; found $table_count tables"

  log "Restoring MySQL snapshot"
  gzip -dc "$package_dir/data/mysql.sql.gz" | compose_at "$install_dir" exec -T mysql sh -c \
    'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD" "$MYSQL_DATABASE"'
}

check_loaded_images() {
  local version=$1
  local image architecture
  for image in "match-v2_java:$version" "match-v2_vue:$version" mysql:8.0 delron/fastdfs:latest registry:2 "${XKP_REGISTRY_IMPORTER_IMAGE:-xkp5/registry-importer:latest}"; do
    architecture=$(docker image inspect --format '{{.Architecture}}' "$image" 2>/dev/null) || die "Image not loaded: $image"
    [[ "$architecture" == amd64 ]] || die "Image $image has unsupported architecture: $architecture"
  done
}

backup_database() {
  local install_dir=$1
  local output_file=$2
  mkdir -p "$(dirname "$output_file")"
  compose_at "$install_dir" exec -T mysql sh -c \
    'exec mysqldump -uroot -p"$MYSQL_ROOT_PASSWORD" --single-transaction --routines --triggers --events "$MYSQL_DATABASE"' \
    | gzip -c > "$output_file"
}

validate_install_config() {
  local install_dir=$1
  if grep -q 'replace-with\|your-server-ip' "$install_dir/.env"; then
    die "Environment file still contains example values: $install_dir/.env"
  fi
  compose_at "$install_dir" config >/dev/null
}
