package com.match.registry.service;

import com.match.registry.dto.ImageReviewRequest;
import com.match.registry.dto.ImageUploadCreateRequest;
import com.match.registry.persistence.*;
import org.junit.*;
import org.junit.rules.TemporaryFolder;
import org.mockito.Mockito;
import org.springframework.mock.web.MockMultipartFile;
import org.springframework.transaction.support.TransactionSynchronization;
import org.springframework.transaction.support.TransactionSynchronizationManager;

import java.nio.file.Files;
import java.nio.file.Path;
import java.io.ByteArrayOutputStream;
import java.security.MessageDigest;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.Collections;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

public class ImageUploadServiceTest {
    @Rule public TemporaryFolder temp = new TemporaryFolder();
    private ImageUploadMapper uploads; private ImageUploadChunkMapper chunks; private ImageArtifactMapper artifacts; private ImageUploadService service;
    @Before public void setUp() { uploads = mock(ImageUploadMapper.class); chunks = mock(ImageUploadChunkMapper.class); artifacts = mock(ImageArtifactMapper.class); service = new ImageUploadService(uploads, chunks, artifacts, temp.getRoot().toPath(), 4096, 16384, Clock.fixed(Instant.parse("2026-08-21T00:00:00Z"), ZoneOffset.UTC)); }
    private ImageUploadCreateRequest request(int total, int chunk) { ImageUploadCreateRequest r = new ImageUploadCreateRequest(); r.setOriginalFilename("image.tar"); r.setTotalSize((long) total); r.setChunkSize(chunk); r.setExpectedSha256("0123456789012345678901234567890123456789012345678901234567890123"); r.setVersion("v1"); r.setGroupId("g"); r.setComponentType("ANNOTATION"); return r; }
    @Test(expected = ImageUploadService.UploadException.class) public void expectedArchiveChecksumIsRequired() { ImageUploadCreateRequest r = request(1, 1); r.setExpectedSha256(null); service.create("SUPER_ADMIN", r, 1); }
    @Test(expected = ImageUploadService.UploadException.class) public void expectedArchiveChecksumMustBeLowercase() { ImageUploadCreateRequest r = request(1, 1); r.setExpectedSha256("A" + r.getExpectedSha256().substring(1)); service.create("SUPER_ADMIN", r, 1); }
    @Test(expected = ImageUploadService.UploadException.class) public void writesRequireSuperAdmin() { service.create("ADMIN", request(1, 1), 1); }
    @Test public void acceptsOutOfOrderChunksAndIdenticalRetry() throws Exception { ImageUploadRecord u = service.create("SUPER_ADMIN", request(4, 2), 1); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectForUpdate(anyString(), anyInt())).thenReturn(null); byte[] a = "ab".getBytes("UTF-8"); String hash = sha(a); service.putChunk("SUPER_ADMIN", u.getUploadId(), 1, new MockMultipartFile("file", a), hash); Path dir=temp.getRoot().toPath().resolve(u.getUploadId()); assertTrue(Files.exists(dir.resolve("1.part"))); assertFalse(Files.exists(dir.resolve("1.reserve"))); assertFalse(Files.exists(dir.resolve("1.part.tmp"))); ImageUploadChunkRecord existing = new ImageUploadChunkRecord(); existing.setUploadId(u.getUploadId()); existing.setChunkIndex(1); existing.setChunkSize(2); existing.setChunkSha256(hash); existing.setStoredBytes(2L); when(chunks.selectForUpdate(u.getUploadId(), 1)).thenReturn(existing); assertEquals(hash, service.putChunk("SUPER_ADMIN", u.getUploadId(), 1, new MockMultipartFile("file", a), hash).getChunkSha256()); }
    @Test public void rejectsConflictingDuplicate() throws Exception { ImageUploadRecord u = service.create("SUPER_ADMIN", request(2, 2), 1); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); ImageUploadChunkRecord e = new ImageUploadChunkRecord(); e.setChunkSha256("00"); e.setChunkIndex(0); e.setChunkSize(2); e.setStoredBytes(2L); when(chunks.selectForUpdate(u.getUploadId(), 0)).thenReturn(e); try { service.putChunk("SUPER_ADMIN", u.getUploadId(), 0, new MockMultipartFile("file", "ab".getBytes()), "11"); fail(); } catch (ImageUploadService.UploadException ex) { assertEquals(ImageUploadService.CODE_CONFLICT, ex.getCode()); } }
    @Test public void reviewIsIdempotent() { ImageArtifactRecord a = new ImageArtifactRecord(); a.setArtifactId("a"); a.setReviewState(ImageUploadService.APPROVED); when(artifacts.selectById("a")).thenReturn(a); ImageReviewRequest r = new ImageReviewRequest(); r.setDecision(ImageUploadService.APPROVED); assertSame(a, service.review("SUPER_ADMIN", "a", r, 1)); verify(artifacts, never()).updateById(any()); }
    @Test public void oppositeReviewDecisionConflicts() { ImageArtifactRecord a=new ImageArtifactRecord(); a.setArtifactId("a"); a.setReviewState(ImageUploadService.APPROVED); when(artifacts.selectPendingReviewForUpdate("a")).thenReturn(null); when(artifacts.selectById("a")).thenReturn(a); ImageReviewRequest r=new ImageReviewRequest(); r.setDecision(ImageUploadService.REJECTED); try { service.review("SUPER_ADMIN","a",r,1); fail(); } catch(ImageUploadService.UploadException e) { assertEquals(ImageUploadService.CODE_STATE,e.getCode()); } }
    @Test(expected=ImageUploadService.UploadException.class) public void excessiveChunkCountRejected() { service.create("SUPER_ADMIN", request(200001,2),1); }
    @Test public void rejectedArtifactReleasesStaging() throws Exception { ImageArtifactRecord a = new ImageArtifactRecord(); a.setArtifactId("a"); a.setReviewState(ImageUploadService.PENDING_REVIEW); ImageUploadRecord u = new ImageUploadRecord(); u.setUploadId("u"); when(artifacts.selectPendingReviewForUpdate("a")).thenReturn(a); when(uploads.selectOne(any())).thenReturn(u); Path p=temp.getRoot().toPath().resolve("u").resolve("archive"); Files.createDirectories(p.getParent()); Files.write(p,new byte[]{1}); ImageReviewRequest r=new ImageReviewRequest(); r.setDecision(ImageUploadService.REJECTED); service.review("SUPER_ADMIN","a",r,1); assertFalse(Files.exists(p)); }
    @Test public void cancelRemovesStagingFiles() throws Exception { ImageUploadRecord u = service.create("SUPER_ADMIN", request(1, 1), 1); Path p = temp.getRoot().toPath().resolve(u.getUploadId()).resolve("0.part"); Files.createDirectories(p.getParent()); Files.write(p, new byte[]{1}); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); service.cancel("SUPER_ADMIN", u.getUploadId()); assertFalse(Files.exists(p)); }
    @Test public void cancelCleanupWaitsForCommit() throws Exception { ImageUploadRecord u=service.create("SUPER_ADMIN",request(1,1),1); Path p=temp.getRoot().toPath().resolve(u.getUploadId()).resolve("0.part"); Files.write(p,new byte[]{1}); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); TransactionSynchronizationManager.initSynchronization(); try { service.cancel("SUPER_ADMIN",u.getUploadId()); assertTrue(Files.exists(p)); for(TransactionSynchronization s:TransactionSynchronizationManager.getSynchronizations()) s.afterCommit(); assertFalse(Files.exists(p)); } finally { TransactionSynchronizationManager.clearSynchronization(); } }
    @Test public void scheduledCleanupRemovesOldOrphanUuidDirectory() throws Exception { String id="11111111-1111-1111-1111-111111111111"; Path dir=temp.getRoot().toPath().resolve(id); Files.createDirectories(dir); Files.write(dir.resolve("x"),new byte[]{1}); Files.setLastModifiedTime(dir,java.nio.file.attribute.FileTime.from(Instant.parse("2026-08-19T00:00:00Z"))); when(uploads.selectList(any())).thenReturn(Collections.emptyList()); when(uploads.selectById(id)).thenReturn(null); service.cleanupExpiredUploads(); assertFalse(Files.exists(dir)); }
    @Test public void scheduledCleanupPreservesArchiveAndRemovesCompletedResidue() throws Exception { String id="22222222-2222-2222-2222-222222222222"; Path dir=temp.getRoot().toPath().resolve(id); Files.createDirectories(dir); Files.write(dir.resolve("archive"),new byte[]{1}); Files.write(dir.resolve("0.part"),new byte[]{1}); Files.write(dir.resolve("0.reserve"),new byte[]{1}); ImageUploadRecord u=new ImageUploadRecord(); u.setUploadId(id); u.setState(ImageUploadService.PENDING_REVIEW); when(uploads.selectList(any())).thenReturn(Collections.emptyList()); when(uploads.selectById(id)).thenReturn(u); service.cleanupExpiredUploads(); assertTrue(Files.exists(dir.resolve("archive"))); assertFalse(Files.exists(dir.resolve("0.part"))); assertFalse(Files.exists(dir.resolve("0.reserve"))); }
    @Test public void scheduledCleanupRemovesOldUntrackedPart() throws Exception { String id="33333333-3333-3333-3333-333333333333"; Path dir=temp.getRoot().toPath().resolve(id); Files.createDirectories(dir); Path part=dir.resolve("7.part"); Files.write(part,new byte[]{1}); Files.setLastModifiedTime(part,java.nio.file.attribute.FileTime.from(Instant.parse("2026-08-20T00:00:00Z"))); ImageUploadRecord u=new ImageUploadRecord(); u.setUploadId(id); u.setState(ImageUploadService.UPLOADING); when(uploads.selectList(any())).thenReturn(Collections.emptyList()); when(uploads.selectById(id)).thenReturn(u); when(chunks.selectByUpload(id)).thenReturn(Collections.emptyList()); service.cleanupExpiredUploads(); assertFalse(Files.exists(part)); }
    @Test public void scheduledCleanupSkipsActiveOldReservation() throws Exception { String id="44444444-4444-4444-4444-444444444444"; Path dir=temp.getRoot().toPath().resolve(id); Files.createDirectories(dir); Path reserve=dir.resolve("7.reserve"), active=dir.resolve("7.active"); Files.write(reserve,new byte[]{1}); java.nio.file.attribute.FileTime old=java.nio.file.attribute.FileTime.from(Instant.parse("2026-08-20T00:00:00Z")); Files.setLastModifiedTime(reserve,old); ImageUploadRecord u=new ImageUploadRecord(); u.setUploadId(id); u.setState(ImageUploadService.UPLOADING); when(uploads.selectList(any())).thenReturn(Collections.emptyList()); when(uploads.selectById(id)).thenReturn(u); when(chunks.selectByUpload(id)).thenReturn(Collections.emptyList()); try(java.nio.channels.FileChannel channel=java.nio.channels.FileChannel.open(active,java.nio.file.StandardOpenOption.CREATE,java.nio.file.StandardOpenOption.WRITE); java.nio.channels.FileLock lock=channel.lock()) { Files.setLastModifiedTime(active,old); service.cleanupExpiredUploads(); assertTrue(Files.exists(reserve)); } }
    @Test public void rejectsWrongLastChunkSize() throws Exception { ImageUploadRecord u = service.create("SUPER_ADMIN", request(3, 2), 1); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectForUpdate(anyString(), anyInt())).thenReturn(null); byte[] bytes = "xx".getBytes(); try { service.putChunk("SUPER_ADMIN", u.getUploadId(), 1, new MockMultipartFile("file", bytes), sha(bytes)); fail(); } catch (ImageUploadService.UploadException ex) { assertEquals(ImageUploadService.CODE_SIZE, ex.getCode()); } }
    @Test public void checksumFailureDeletesTemporaryPart() throws Exception { ImageUploadRecord u = service.create("SUPER_ADMIN", request(2, 2), 1); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectForUpdate(anyString(), anyInt())).thenReturn(null); try { service.putChunk("SUPER_ADMIN", u.getUploadId(), 0, new MockMultipartFile("file", "ab".getBytes()), request(1,1).getExpectedSha256()); fail(); } catch (ImageUploadService.UploadException expected) { assertFalse(Files.exists(temp.getRoot().toPath().resolve(u.getUploadId()).resolve("0.reserve"))); } }
    @Test public void streamingUsesOnlyPreSizedReservation() throws Exception { byte[] data="ab".getBytes("UTF-8"); ImageUploadRecord u=service.create("SUPER_ADMIN",request(2,2),1); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectForUpdate(anyString(),anyInt())).thenReturn(null); Path dir=temp.getRoot().toPath().resolve(u.getUploadId()); java.io.ByteArrayInputStream input=new java.io.ByteArrayInputStream(data) { boolean checked; @Override public synchronized int read(byte[] b,int off,int len) { if(!checked) { checked=true; assertTrue(Files.exists(dir.resolve("0.reserve"))); assertFalse(Files.exists(dir.resolve("0.part.tmp"))); try { assertEquals(2,Files.size(dir.resolve("0.reserve"))); } catch(Exception e) { throw new AssertionError(e); } } return super.read(b,off,len); } }; service.putChunk("SUPER_ADMIN",u.getUploadId(),0,input,2,sha(data)); assertTrue(Files.exists(dir.resolve("0.part"))); }
    @Test public void retryReusesPostMovePartWithoutSecondWrite() throws Exception { byte[] data="ab".getBytes("UTF-8"); ImageUploadRecord u=service.create("SUPER_ADMIN",request(2,2),1); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectForUpdate(anyString(),anyInt())).thenReturn(null); Path dir=temp.getRoot().toPath().resolve(u.getUploadId()); Files.write(dir.resolve("0.part"),data); service.putChunk("SUPER_ADMIN",u.getUploadId(),0,new java.io.ByteArrayInputStream(new byte[0]),2,sha(data)); assertFalse(Files.exists(dir.resolve("0.reserve"))); Path active=dir.resolve("0.active"); assertTrue(Files.exists(active)); try(java.nio.channels.FileChannel first=java.nio.channels.FileChannel.open(active,java.nio.file.StandardOpenOption.WRITE);java.nio.channels.FileLock ignored=first.lock()){} assertTrue(Files.exists(active)); try(java.nio.channels.FileChannel second=java.nio.channels.FileChannel.open(active,java.nio.file.StandardOpenOption.WRITE);java.nio.channels.FileLock ignored=second.lock()){} verify(chunks).insertOrRetry(eq(u.getUploadId()),eq(0),eq(2),eq(sha(data)),eq(2L),any()); }
    @Test public void activityLeaseUsesBoundedLockStriping() throws Exception { Class<?> lease=Class.forName("com.match.registry.service.ImageUploadService$ActivityLease"); java.lang.reflect.Field stripes=lease.getDeclaredField("JVM_LOCK_STRIPES"); stripes.setAccessible(true); assertEquals(1024,java.lang.reflect.Array.getLength(stripes.get(null))); try { lease.getDeclaredField("JVM_LOCKS"); fail(); } catch(NoSuchFieldException expected) { } }
    @Test public void validDockerSaveReachesReviewAndBadHeaderIsRejected() throws Exception { byte[] tar = dockerTar(); ImageUploadCreateRequest r = request(tar.length, tar.length); r.setExpectedSha256(sha(tar)); ImageUploadRecord u = service.create("SUPER_ADMIN", r, 1); u.setReceivedBytes((long) tar.length); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); ImageUploadChunkRecord c = new ImageUploadChunkRecord(); c.setChunkIndex(0); c.setStoredBytes((long) tar.length); when(chunks.selectByUpload(u.getUploadId())).thenReturn(Collections.singletonList(c)); Path part = temp.getRoot().toPath().resolve(u.getUploadId()).resolve("0.part"); Files.write(part, tar); assertEquals(ImageUploadService.PENDING_REVIEW, service.complete("SUPER_ADMIN", u.getUploadId()).getState()); tar[148] ^= 1; r.setArtifactId("other"); r.setExpectedSha256(sha(tar)); ImageUploadRecord bad = service.create("SUPER_ADMIN", r, 1); bad.setReceivedBytes((long) tar.length); when(uploads.selectForUpdate(bad.getUploadId())).thenReturn(bad); when(chunks.selectByUpload(bad.getUploadId())).thenReturn(Collections.singletonList(c)); Files.write(temp.getRoot().toPath().resolve(bad.getUploadId()).resolve("0.part"), tar); try { service.complete("SUPER_ADMIN", bad.getUploadId()); fail(); } catch (ImageUploadService.UploadException e) { assertEquals(ImageUploadService.CODE_ARCHIVE, e.getCode()); } }
    @Test public void dockerManifestMissingReferencedConfigIsRejected() throws Exception { byte[] json="[{\"Config\":\"missing.json\",\"Layers\":[]}]".getBytes("UTF-8"); ByteArrayOutputStream out=new ByteArrayOutputStream(); tarEntry(out,"manifest.json",json); out.write(new byte[1024]); byte[] tar=out.toByteArray(); ImageUploadCreateRequest r=request(tar.length,tar.length); r.setExpectedSha256(sha(tar)); ImageUploadRecord u=service.create("SUPER_ADMIN",r,1); u.setReceivedBytes((long)tar.length); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectByUpload(u.getUploadId())).thenReturn(Collections.singletonList(new ImageUploadChunkRecord())); Files.write(temp.getRoot().toPath().resolve(u.getUploadId()).resolve("0.part"),tar); try { service.complete("SUPER_ADMIN",u.getUploadId()); fail(); } catch(ImageUploadService.UploadException e) { assertEquals(ImageUploadService.CODE_ARCHIVE,e.getCode()); } }
    @Test public void completionReusesPostMoveArchiveWithoutParts() throws Exception { byte[] tar=dockerTar(); ImageUploadCreateRequest r=request(tar.length,tar.length); r.setExpectedSha256(sha(tar)); ImageUploadRecord u=service.create("SUPER_ADMIN",r,1); u.setReceivedBytes((long)tar.length); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectByUpload(u.getUploadId())).thenReturn(Collections.singletonList(new ImageUploadChunkRecord())); Path dir=temp.getRoot().toPath().resolve(u.getUploadId()); Files.write(dir.resolve("archive"),tar); assertEquals(ImageUploadService.PENDING_REVIEW,service.complete("SUPER_ADMIN",u.getUploadId()).getState()); assertFalse(Files.exists(dir.resolve("archive.reserve"))); }
    @Test public void recoveredArchiveChecksumMismatchHasStableCode() throws Exception { byte[] tar=dockerTar(); ImageUploadCreateRequest r=request(tar.length,tar.length); r.setExpectedSha256(sha(tar)); ImageUploadRecord u=service.create("SUPER_ADMIN",r,1); u.setReceivedBytes((long)tar.length); when(uploads.selectForUpdate(u.getUploadId())).thenReturn(u); when(chunks.selectByUpload(u.getUploadId())).thenReturn(Collections.singletonList(new ImageUploadChunkRecord())); tar[600]^=1; Files.write(temp.getRoot().toPath().resolve(u.getUploadId()).resolve("archive"),tar); try { service.complete("SUPER_ADMIN",u.getUploadId()); fail(); } catch(ImageUploadService.UploadException e) { assertEquals(ImageUploadService.CODE_CHECKSUM,e.getCode()); } }
    private byte[] dockerTar() throws Exception { byte[] json = "[{\"Config\":\"config.json\",\"RepoTags\":[\"x:v1\"],\"Layers\":[]}]".getBytes("UTF-8"); ByteArrayOutputStream out=new ByteArrayOutputStream(); tarEntry(out,"manifest.json",json); tarEntry(out,"config.json","{}".getBytes("UTF-8")); out.write(new byte[1024]); return out.toByteArray(); }
    private void tarEntry(ByteArrayOutputStream out,String filename,byte[] content) throws Exception { byte[] h=new byte[512]; byte[] name=filename.getBytes("UTF-8"); System.arraycopy(name,0,h,0,name.length); putOctal(h,100,8,0644); putOctal(h,124,12,content.length); for(int i=148;i<156;i++) h[i]=32; h[156]='0'; byte[] magic="ustar".getBytes("UTF-8"); System.arraycopy(magic,0,h,257,magic.length); long sum=0; for(byte b:h) sum+=b&255; putOctal(h,148,8,sum); out.write(h); out.write(content); out.write(new byte[(512-content.length%512)%512]); }
    private void putOctal(byte[] b,int off,int len,long v) throws Exception { String s=String.format("%0"+(len-1)+"o",v); byte[] x=s.getBytes("US-ASCII"); System.arraycopy(x,0,b,off,x.length); b[off+len-1]=0; }
    private String sha(byte[] b) throws Exception { byte[] d = MessageDigest.getInstance("SHA-256").digest(b); StringBuilder s = new StringBuilder(); for (byte x : d) s.append(String.format("%02x", x)); return s.toString(); }
}
