<template>
  <section class="module-page module-composed-page">
    <header class="module-heading"><div><h1>课程管理</h1><p>创建课程、维护课程资源并控制发布状态。</p></div><el-button type="primary" icon="el-icon-plus" @click="openCourse()">新建课程</el-button></header>
    <div class="module-table-wrap"><el-table v-loading="loading" :data="courses" empty-text="暂无课程">
      <el-table-column label="课程名称" min-width="190"><template slot-scope="s">{{ s.row.course.name }}</template></el-table-column><el-table-column label="课程类别" width="140"><template slot-scope="s">{{ s.row.course.courseType }}</template></el-table-column><el-table-column label="资源" width="80"><template slot-scope="s">{{ s.row.resources.length }}</template></el-table-column><el-table-column label="状态" width="100"><template slot-scope="s"><el-tag size="small" :type="s.row.course.enabled ? 'success' : 'info'">{{ s.row.course.enabled ? '已发布' : '草稿' }}</el-tag></template></el-table-column>
      <el-table-column label="操作" width="300" align="right"><template slot-scope="s"><el-button size="small" @click="openCourse(s.row.course)">编辑</el-button><el-button size="small" @click="openResource(s.row.course)">添加资源</el-button><el-button size="small" :type="s.row.course.enabled ? 'warning' : 'success'" @click="toggle(s.row.course)">{{ s.row.course.enabled ? '停用' : '发布' }}</el-button></template></el-table-column>
    </el-table></div>
    <el-dialog :title="editing ? '编辑课程' : '新建课程'" :visible.sync="courseDialog" width="500px"><el-form :model="form" label-width="90px"><el-form-item label="课程名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="课程类别"><el-input v-model="form.courseType" /></el-form-item><el-form-item label="课程简介"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item></el-form><span slot="footer"><el-button @click="courseDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveCourse">保存</el-button></span></el-dialog>
    <el-dialog title="添加课程资源" :visible.sync="resourceDialog" width="520px"><el-form :model="resource" label-width="90px"><el-form-item label="资源类型"><el-select v-model="resource.resourceType" style="width:100%"><el-option v-for="item in resourceTypes" :key="item" :label="item" :value="item" /></el-select></el-form-item><el-form-item label="资源名称"><el-input v-model="resource.name" /></el-form-item><el-form-item label="存储标识"><el-input v-model="resource.storageKey" /></el-form-item><el-form-item label="SHA-256"><el-input v-model="resource.sha256" /></el-form-item></el-form><span slot="footer"><el-button @click="resourceDialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveResource">添加</el-button></span></el-dialog>
  </section>
</template>
<script>
import { listAdminCourses, createCourse, updateCourse, setCourseEnabled, addCourseResource } from '@/api/Courses'
export default { data: () => ({ loading: false, saving: false, courses: [], courseDialog: false, resourceDialog: false, editing: false, selectedCourse: null, form: { name: '', courseType: '', description: '' }, resource: { resourceType: 'EBOOK', name: '', storageKey: '', sha256: '' }, resourceTypes: ['EBOOK', 'VIDEO', 'PPT', 'ARCHIVE'] }), created () { this.load() }, methods: { async load () { this.loading = true; try { const r = await listAdminCourses(); this.courses = r.data || [] } finally { this.loading = false } }, openCourse (course) { this.editing = !!course; this.form = course ? Object.assign({}, course) : { name: '', courseType: '', description: '' }; this.courseDialog = true }, async saveCourse () { this.saving = true; try { await (this.editing ? updateCourse(this.form.courseId, this.form) : createCourse(this.form)); this.courseDialog = false; this.$message.success('课程已保存'); await this.load() } finally { this.saving = false } }, async toggle (course) { await setCourseEnabled(course.courseId, !course.enabled); this.load() }, openResource (course) { this.selectedCourse = course; this.resourceDialog = true }, async saveResource () { this.saving = true; try { await addCourseResource(this.selectedCourse.courseId, this.resource); this.resourceDialog = false; await this.load() } finally { this.saving = false } } } }
</script>
