<template>
  <section class="resource-browser">
    <header class="resource-toolbar"><div class="breadcrumbs"><button v-for="(item,index) in breadcrumbs" :key="index" @click="$emit('navigate',item,index)">{{ item.name }}</button></div><div><el-button v-if="canCreateDirectory" size="small" icon="el-icon-folder-add" @click="$emit('create-directory')">新建目录</el-button><el-button v-if="canUpload" size="small" type="primary" icon="el-icon-upload2" @click="$emit('upload')">上传文件</el-button></div></header>
    <div class="resource-table"><el-table v-loading="loading" :data="rows" empty-text="当前目录为空"><el-table-column label="名称" min-width="260"><template slot-scope="s"><button class="entry-name" @click="open(s.row)"><i :class="s.row.kind==='directory'?'el-icon-folder':'el-icon-document'" /><span>{{ s.row.name || s.row.fileName }}</span></button></template></el-table-column><el-table-column label="大小" width="110"><template slot-scope="s">{{ s.row.kind==='directory'?'--':formatSize(s.row.contentLength) }}</template></el-table-column><el-table-column label="上传人" width="100"><template slot-scope="s">{{ s.row.uploadedBy || s.row.createdBy || '--' }}</template></el-table-column><el-table-column label="时间" width="170"><template slot-scope="s">{{ formatTime(s.row.updatedAt || s.row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="300" align="right"><template slot-scope="s"><template v-if="s.row.kind==='file'"><el-button size="mini" @click="$emit('download',s.row)">下载</el-button><el-button v-if="allowDeliver" size="mini" type="primary" plain @click="$emit('deliver',s.row)">{{ deliverLabel }}</el-button></template><el-button v-if="canRemove(s.row)" size="mini" type="danger" plain @click="$emit('remove',s.row)">删除</el-button></template></el-table-column></el-table></div>
  </section>
</template>
<script>
export default {props:{directories:{type:Array,default:()=>[]},files:{type:Array,default:()=>[]},breadcrumbs:{type:Array,default:()=>[{name:'根目录',id:null}]},loading:Boolean,canUpload:Boolean,canCreateDirectory:Boolean,allowDeliver:Boolean,deliverLabel:{type:String,default:'发送到容器'},canDelete:{type:[Boolean,Function],default:false}},computed:{rows(){return this.directories.map(item=>Object.assign({kind:'directory'},item)).concat(this.files.map(item=>Object.assign({kind:'file'},item)))}},methods:{open(row){if(row.kind==='directory')this.$emit('open-directory',row);else this.$emit('preview',row)},canRemove(row){return typeof this.canDelete==='function'?this.canDelete(row):this.canDelete},formatSize(bytes){if(bytes==null)return'--';const units=['B','KB','MB','GB'];let value=Number(bytes),index=0;while(value>=1024&&index<3){value/=1024;index++}return `${index&&value<10?value.toFixed(1):Math.round(value)} ${units[index]}`},formatTime(value){if(!value)return'--';const date=new Date(value);return Number.isNaN(date.getTime())?'--':date.toLocaleString('zh-CN',{hour12:false})}}}
</script>
.resource-table .el-button--primary.is-plain{color:#fff;background:var(--ui-primary);border-color:var(--ui-primary)}.resource-table .el-button--primary.is-plain{color:#fff;background:var(--ui-primary);border-color:var(--ui-primary)}.resource-table .el-button--primary.is-plain{color:#fff;background:var(--ui-primary);border-color:var(--ui-primary)}<style scoped>.resource-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.breadcrumbs{display:flex;align-items:center;min-width:0;overflow:hidden}.breadcrumbs button{padding:5px;color:var(--ui-primary);white-space:nowrap;background:transparent;border:0;cursor:pointer}.breadcrumbs button+button:before{margin-right:8px;color:var(--ui-muted);content:'/'}.resource-table{border:1px solid var(--ui-border)}.entry-name{display:flex;align-items:center;gap:8px;max-width:100%;padding:0;color:var(--ui-text);background:transparent;border:0;cursor:pointer}.entry-name i{color:var(--ui-primary);font-size:18px}.entry-name span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:620px){.resource-toolbar{align-items:stretch;flex-direction:column}.resource-toolbar>div:last-child{display:flex}.resource-toolbar .el-button{flex:1;margin-left:0}}</style>
