SET @paper_a_module_a_sort = COALESCE((
    SELECT MAX(sort_order) FROM subject WHERE test_paper_type = 'A' AND modular = 'A'
), 0);
SET @paper_a_module_b_sort = COALESCE((
    SELECT MAX(sort_order) FROM subject WHERE test_paper_type = 'A' AND modular = 'B'
), 0);
SET @paper_a_module_c_sort = COALESCE((
    SELECT MAX(sort_order) FROM subject WHERE test_paper_type = 'A' AND modular = 'C'
), 0);
SET @paper_a_module_d_sort = COALESCE((
    SELECT MAX(sort_order) FROM subject WHERE test_paper_type = 'A' AND modular = 'D'
), 0);
SET @paper_a_module_e_sort = COALESCE((
    SELECT MAX(sort_order) FROM subject WHERE test_paper_type = 'A' AND modular = 'E'
), 0);

INSERT INTO subject (
    subject_creation_time,
    modular,
    modular_name,
    test_paper_type,
    subject_type,
    subject_options,
    sort_order,
    subject_name,
    score,
    answering,
    screenshot_requirement,
    point,
    subject_identification
) VALUES
    (CURRENT_TIMESTAMP, 'A', '工程环境准备', 'A', 'practical', NULL, @paper_a_module_a_sort + 1,
     '离线创建 conda 虚拟环境 contest（Python3.7）', 0,
     '使用 conda 离线模式创建名称为 contest、Python 版本 3.7 的虚拟环境。',
     '环境创建完成终端截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'A', '工程环境准备', 'A', 'practical', NULL, @paper_a_module_a_sort + 2,
     '激活 contest 虚拟环境', 0,
     '执行环境激活命令，确认终端提示符显示 contest 标识。',
     '环境激活成功终端截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'A', '工程环境准备', 'A', 'practical', NULL, @paper_a_module_a_sort + 3,
     'conda 离线安装 tensorflow-gpu==1.15', 0,
     '依托本地 conda 缓存离线安装 GPU 版 TensorFlow 1.15，适配 Python 3.7。',
     'tensorflow-gpu 安装完成、版本校验截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'A', '工程环境准备', 'A', 'practical', NULL, @paper_a_module_a_sort + 4,
     'pip 离线批量安装第三方依赖', 0,
     '在平台【帮助】板块下载环境依赖清单，使用本地离线 whl 包批量安装清单内所有依赖。',
     '全部依赖安装完成终端截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'A', '工程环境准备', 'A', 'practical', NULL, @paper_a_module_a_sort + 5,
     '离线安装自定义目标检测库', 0,
     '操作 1：下载 zy_od_1.0.tar 源码包，通过 pip 本地离线安装；操作 2：下载 zy_slim_1.0.tar 源码包，通过 pip 本地离线安装。',
     'zy_od 库和 zy_slim 库安装完成截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'A', '工程环境准备', 'A', 'practical', NULL, @paper_a_module_a_sort + 6,
     '运行脚本校验环境完整性', 0,
     '下载平台环境验证脚本并执行，无报错即代表环境可用。',
     '脚本运行校验通过截图。', NULL, NULL),

    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 1,
     '数据集下载并解压至指定目录', 0,
     '操作 1：从数据平台下载原始数据集文件 u1.tar.gz；操作 2：将 u1.tar.gz 完整解压至 /home/student/data。',
     '数据集下载完成界面截图和解压后目录文件列表截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 2,
     '数据集清洗，筛选不合格样本', 0,
     '遍历全部图像，剔除模糊度过高、干扰类别、破损无效等不规范图片。',
     '筛选出的不合格样本原图截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 3,
     '数据集划分并创建标注任务', 0,
     '将清洗后数据集拆分为训练集、验证集，分别创建标注任务并完成目标标注。',
     '训练集任务创建完成截图和验证集任务创建完成截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 4,
     '新建图像增强专用虚拟环境 contest1', 0,
     '退出 contest 环境，使用 conda 离线创建 contest1，指定 Python 3.7。',
     'contest1 环境创建完成截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 5,
     '离线安装图像增强依赖库', 0,
     '在 contest1 环境中，使用 pip 离线安装 OpenCV、imgaug 库。',
     '两个库全部安装完成终端截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 6,
     '中值滤波图像去噪', 0,
     '从平台【帮助】下载中值滤波代码和噪声原图 noise.jpg；运行代码完成去噪，输出 denoise.jpg。',
     '处理后 denoise.jpg 效果图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'B', '数据标注与增强', 'A', 'practical', NULL, @paper_a_module_b_sort + 7,
     '图像亮度增强处理', 0,
     '从平台【帮助】下载亮度增强代码和低亮度原图 dark.jpg；运行代码提亮图像，输出 bright.jpg。',
     '处理后 bright.jpg 效果图。', NULL, NULL),

    (CURRENT_TIMESTAMP, 'C', '模型搭建与训练', 'A', 'practical', NULL, @paper_a_module_c_sort + 1,
     '预训练模型下载与解压', 0,
     '统一工作根目录为 /home/student/contest。操作 1：下载预训练模型压缩包；操作 2：将预训练模型解压至 /home/student/contest。',
     '模型包下载完成截图和解压后目录文件列表截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'C', '模型搭建与训练', 'A', 'practical', NULL, @paper_a_module_c_sort + 2,
     '部署模型训练程序', 0,
     '下载全套训练脚本，存放至 /home/student/contest。',
     '脚本目录文件截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'C', '模型搭建与训练', 'A', 'practical', NULL, @paper_a_module_c_sort + 3,
     '部署训练数据集', 0,
     '下载划分完成的训练集，存放至 /home/student/contest/data。',
     '目录内训练集文件截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'C', '模型搭建与训练', 'A', 'practical', NULL, @paper_a_module_c_sort + 4,
     '部署训练标签文件', 0,
     '下载配套标注标签文件，存放至 /home/student/contest/data。',
     '目录内标签文件截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'C', '模型搭建与训练', 'A', 'practical', NULL, @paper_a_module_c_sort + 5,
     '执行完整模型训练', 0,
     '运行训练主程序，完成全部训练轮次，无中断报错。',
     '训练结束日志截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'C', '模型搭建与训练', 'A', 'practical', NULL, @paper_a_module_c_sort + 6,
     'TensorBoard 可视化训练总损失', 0,
     '启动 TensorBoard 读取训练日志，查看 losses 下 TotalLoss 曲线，分析模型收敛效果。',
     'TensorBoard 可视化界面截图。', NULL, NULL),

    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 1,
     '部署模型评估程序', 0,
     '下载评估脚本，存放至 /home/student/contest。',
     '脚本目录文件截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 2,
     '部署验证数据集', 0,
     '下载划分完成的验证集，存放至 /home/student/contest/data。',
     '目录内验证集文件截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 3,
     '执行模型评估程序', 0,
     '运行评估脚本，输出 mAP、各类别精度、定位损失等指标。',
     '评估运行完成日志截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 4,
     'TensorBoard 可视化验证定位损失', 0,
     '打开 TensorBoard 查看 losses 下 Loss/localization_loss 曲线，分析模型泛化能力。',
     '定位损失可视化界面截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 5,
     '修改配置完成多轮调参对比实验', 0,
     '修改 model.config 文件中超参数，完成三次不同参数二次训练，对比每轮训练总损失与评估精度。',
     '三次实验 Loss、精度对比截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 6,
     '导出冻结推理模型', 0,
     '下载并执行模型冻结导出程序，固化训练权重为冻结图文件。',
     '冻结模型导出成功终端截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'D', '算法模型优化', 'A', 'practical', NULL, @paper_a_module_d_sort + 7,
     '单图目标检测推理测试', 0,
     '运行检测程序读取 /home/student/contest/test.jpg，绘制目标检测框并将结果保存为 /home/student/contest/out_test.jpg。',
     '带检测框的 out_test.jpg 结果图。', NULL, NULL),

    (CURRENT_TIMESTAMP, 'E', '算法模型应用部署', 'A', 'practical', NULL, @paper_a_module_e_sort + 1,
     '执行 TFLite 预处理转换脚本', 0,
     '下载并运行【创建 tflite】程序，完成轻量化预处理。',
     '转换执行成功日志截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'E', '算法模型应用部署', 'A', 'practical', NULL, @paper_a_module_e_sort + 2,
     '生成推理文件 detection.tflite', 0,
     '运行完整模型转换程序，输出标准移动端推理文件 detection.tflite。',
     '目录内 detection.tflite 文件截图。', NULL, NULL),
    (CURRENT_TIMESTAMP, 'E', '算法模型应用部署', 'A', 'practical', NULL, @paper_a_module_e_sort + 3,
     '端侧部署文件拷贝', 0,
     '将推理程序、detection.tflite 模型文件复制至 /usr/local/zy-T100/utils_x86。',
     '目标目录全部文件列表截图。', NULL, NULL);
