CREATE TABLE processing_agent_command (
    command_id VARCHAR(36) NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    command_type VARCHAR(32) NOT NULL,
    command_version SMALLINT UNSIGNED NOT NULL,
    payload_json JSON NOT NULL,
    state VARCHAR(32) NOT NULL,
    active_dedup_key VARCHAR(128) NULL,
    requester_user_id INT NULL,
    requester_role VARCHAR(32) NOT NULL,
    correlation_id VARCHAR(36) NOT NULL,
    requested_at DATETIME(3) NOT NULL,
    available_at DATETIME(3) NOT NULL,
    lease_token VARCHAR(36) NULL,
    lease_expires_at DATETIME(3) NULL,
    attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    delivered_at DATETIME(3) NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    result_code VARCHAR(64) NULL,
    result_message VARCHAR(512) NULL,
    result_json JSON NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (command_id),
    UNIQUE KEY uk_agent_active_command (active_dedup_key),
    KEY idx_agent_command_poll (agent_id, state, available_at),
    KEY idx_agent_command_history (agent_id, requested_at),
    KEY idx_agent_command_completion (completed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
