CREATE TABLE processing_environment_slot (
    slot_id VARCHAR(36) NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    slot_number TINYINT UNSIGNED NOT NULL,
    user_id INT NOT NULL,
    created_by INT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (slot_id),
    UNIQUE KEY uk_processing_environment_slot (agent_id, slot_number),
    UNIQUE KEY uk_processing_environment_user (agent_id, user_id),
    KEY idx_processing_environment_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE container_template (
    template_version_id VARCHAR(36) NOT NULL,
    template_id VARCHAR(36) NOT NULL,
    template_version SMALLINT UNSIGNED NOT NULL,
    template_name VARCHAR(80) NOT NULL,
    component_type VARCHAR(16) NOT NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    image_reference VARCHAR(255) NOT NULL,
    runtime_name VARCHAR(32) NOT NULL,
    restart_policy VARCHAR(16) NOT NULL,
    ports_json JSON NOT NULL,
    mount_target VARCHAR(255) NOT NULL,
    command_json JSON NULL,
    working_directory VARCHAR(255) NULL,
    cpu_limit_millis INT UNSIGNED NULL,
    memory_limit_bytes BIGINT UNSIGNED NULL,
    gpu_enabled TINYINT(1) NOT NULL DEFAULT 0,
    gpu_compute_percent TINYINT UNSIGNED NULL,
    gpu_memory_limit_bytes BIGINT UNSIGNED NULL,
    config_fingerprint CHAR(64) NOT NULL,
    created_by INT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    published_at DATETIME(3) NOT NULL,
    disabled_at DATETIME(3) NULL,
    PRIMARY KEY (template_version_id),
    UNIQUE KEY uk_container_template_version (template_id, template_version),
    UNIQUE KEY uk_container_template_fingerprint (config_fingerprint),
    KEY idx_container_template_type (component_type, enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE training_environment (
    environment_id VARCHAR(36) NOT NULL,
    user_id INT NOT NULL,
    course_id INT NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    slot_id VARCHAR(36) NOT NULL,
    slot_number TINYINT UNSIGNED NOT NULL,
    annotation_template_id VARCHAR(36) NOT NULL,
    annotation_template_version SMALLINT UNSIGNED NOT NULL,
    editor_template_id VARCHAR(36) NOT NULL,
    editor_template_version SMALLINT UNSIGNED NOT NULL,
    workspace_relative_path VARCHAR(512) NOT NULL,
    desired_state VARCHAR(24) NOT NULL,
    actual_state VARCHAR(24) NOT NULL,
    annotation_container_name VARCHAR(128) NOT NULL,
    annotation_container_state VARCHAR(24) NOT NULL,
    editor_container_name VARCHAR(128) NOT NULL,
    editor_container_state VARCHAR(24) NOT NULL,
    current_operation_id VARCHAR(36) NULL,
    lock_version BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by INT NOT NULL,
    created_at DATETIME(3) NOT NULL,
    updated_by INT NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (environment_id),
    UNIQUE KEY uk_training_environment_assignment (user_id, course_id),
    UNIQUE KEY uk_training_environment_annotation_name (annotation_container_name),
    UNIQUE KEY uk_training_environment_editor_name (editor_container_name),
    KEY idx_environment_agent_state (agent_id, actual_state),
    KEY idx_environment_slot (slot_id, actual_state),
    KEY idx_environment_user_state (user_id, desired_state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE environment_port_allocation (
    allocation_id VARCHAR(36) NOT NULL,
    slot_id VARCHAR(36) NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    component_type VARCHAR(16) NOT NULL,
    container_port INT UNSIGNED NOT NULL,
    host_port INT UNSIGNED NOT NULL,
    protocol VARCHAR(8) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (allocation_id),
    UNIQUE KEY uk_environment_agent_port (agent_id, host_port, protocol),
    UNIQUE KEY uk_environment_slot_container_port (slot_id, component_type, container_port, protocol),
    KEY idx_environment_port_slot (slot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE environment_operation (
    operation_id VARCHAR(36) NOT NULL,
    environment_id VARCHAR(36) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    actor_user_id INT NOT NULL,
    actor_role VARCHAR(32) NOT NULL,
    command_id VARCHAR(36) NULL,
    state VARCHAR(24) NOT NULL,
    active_operation_key VARCHAR(128) NULL,
    correlation_id VARCHAR(36) NOT NULL,
    requested_at DATETIME(3) NOT NULL,
    started_at DATETIME(3) NULL,
    completed_at DATETIME(3) NULL,
    result_code VARCHAR(64) NULL,
    result_message VARCHAR(512) NULL,
    component_results_json JSON NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (operation_id),
    UNIQUE KEY uk_environment_active_operation (active_operation_key),
    KEY idx_environment_operation_environment (environment_id, requested_at),
    KEY idx_environment_operation_command (command_id),
    KEY idx_environment_operation_state (state, requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
