CREATE TABLE processing_agent_terminal_session (
    session_id VARCHAR(36) NOT NULL,
    agent_id VARCHAR(36) NOT NULL,
    requester_user_id INT NOT NULL,
    requester_role VARCHAR(32) NOT NULL,
    state VARCHAR(24) NOT NULL,
    active_agent_id VARCHAR(36) NULL,
    agent_ticket_digest CHAR(64) NULL,
    agent_ticket_expires_at DATETIME(3) NULL,
    agent_ticket_consumed_at DATETIME(3) NULL,
    browser_ticket_digest CHAR(64) NULL,
    browser_ticket_expires_at DATETIME(3) NULL,
    browser_ticket_consumed_at DATETIME(3) NULL,
    command_id VARCHAR(36) NULL,
    requested_at DATETIME(3) NOT NULL,
    agent_connected_at DATETIME(3) NULL,
    browser_connected_at DATETIME(3) NULL,
    active_at DATETIME(3) NULL,
    last_io_at DATETIME(3) NULL,
    absolute_expires_at DATETIME(3) NOT NULL,
    ended_at DATETIME(3) NULL,
    end_reason VARCHAR(64) NULL,
    end_message VARCHAR(512) NULL,
    browser_to_agent_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    agent_to_browser_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (session_id),
    UNIQUE KEY uk_terminal_active_agent (active_agent_id),
    UNIQUE KEY uk_terminal_command_id (command_id),
    KEY idx_terminal_state_expiry (state, absolute_expires_at),
    KEY idx_terminal_agent_history (agent_id, requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
